
theme: jekyll-theme-cayman
title: "Basicis - Project"
description: "As the name says, it is made to be basic and direct."
logo: "storage/assets/img/logo.png"
show_downloads: true
staticman:
  branch: "gh-pages"