
theme: jekyll-theme-minimal
title: "Basicis - Framework"
description: "As the name says, it is made to be basic and direct."
logo: "https://raw.githubusercontent.com/basicis/core/master/storage/assets/img/logo.png"
show_downloads: true
staticman:
  branch: "gh-pages"